# Generated by Django 5.2.7 on 2025-11-14 07:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Teacher',
                'db_table': 'teachers',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punctuality', models.PositiveSmallIntegerField()),
                ('clarity', models.PositiveSmallIntegerField()),
                ('justice', models.PositiveSmallIntegerField()),
                ('support', models.PositiveSmallIntegerField()),
                ('flexibility', models.PositiveSmallIntegerField()),
                ('knowledge', models.PositiveSmallIntegerField()),
                ('methodology', models.PositiveSmallIntegerField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='teachers.teacher')),
            ],
            options={
                'verbose_name': 'Review',
                'db_table': 'reviews',
                'ordering': ['-created_at'],
            },
        ),
    ]
