# Generated by Django 5.2.7 on 2025-11-14 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='uuid',
            field=models.UUIDField(null=True),
        ),
    ]
