# Generated by Django 5.2.7 on 2025-11-14 16:06. Edited to add UUID field to Teacher model.
from django.db import migrations
import uuid

from django.db import migrations, models

def gen_uuids(apps, schema_editor):
    Teacher = apps.get_model('teachers', 'Teacher')
    for row in Teacher.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=['uuid'])


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_teacher_uuid'),
    ]

    operations = [
        migrations.RunPython(gen_uuids, reverse_code=migrations.RunPython.noop),
    ]
