# Generated by Django 5.2.7 on 2025-11-14 16:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_populate_teacher_uuids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
