# Generated by Django 5.2.7 on 2025-11-16 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0006_teacher_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('teachers', models.ManyToManyField(related_name='subjects', to='teachers.teacher')),
            ],
            options={
                'verbose_name': 'Subject',
                'db_table': 'subjects',
            },
        ),
    ]
