# Generated by Django 5.2.7 on 2025-11-16 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0007_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='teachers',
            field=models.ManyToManyField(blank=True, null=True, related_name='subjects', to='teachers.teacher'),
        ),
    ]
