# Generated by Django 5.2.7 on 2025-11-23 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0008_alter_subject_teachers'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='teachers.subject'),
        ),
    ]
