# Generated by Django 5.2.7 on 2025-12-04 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0009_review_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='careers', to='teachers.department')),
                ('subjects', models.ManyToManyField(related_name='careers', to='teachers.subject')),
            ],
            options={
                'verbose_name': 'Career',
                'db_table': 'careers',
            },
        ),
    ]
