# Generated by Django 5.2.7 on 2025-12-04 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0010_career'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='subjects',
            field=models.ManyToManyField(blank=True, null=True, related_name='careers', to='teachers.subject'),
        ),
    ]
