# Generated by Django 5.2.7 on 2026-01-03 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0012_subject_credits_profile_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='completion_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
