# Generated by Django 5.2.7 on 2026-01-04 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0013_enrollment_completion_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='review',
        ),
        migrations.RemoveField(
            model_name='review',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='review',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
        migrations.AddField(
            model_name='profile',
            name='onboarding_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='review',
            name='enrollment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='teachers.enrollment'),
        ),
        migrations.AlterField(
            model_name='career',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='careers', to='teachers.subject'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('NT', 'Not taken'), ('IP', 'In progress'), ('CM', 'Completed')], default='NT', max_length=2),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='teachers.profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='career',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='teachers.career'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='teachers',
            field=models.ManyToManyField(blank=True, related_name='subjects', to='teachers.teacher'),
        ),
    ]
