# Generated by Django 5.2.7 on 2026-01-06 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0014_remove_enrollment_review_remove_review_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='period',
            field=models.IntegerField(default=0, max_length=12),
        ),
    ]
