# Generated by Django 6.0.1 on 2026-01-12 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0015_subject_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments', to='teachers.subject'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments', to='teachers.teacher'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='period',
            field=models.IntegerField(default=0),
        ),
    ]
