# Generated by Django 6.0.1 on 2026-02-14 08:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0018_alter_subject_options_alter_profile_state_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RankTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_name', models.CharField(max_length=100)),
                ('min_rate', models.FloatField(help_text='The minimum completion rate required for this rank (0.0 to 1.0)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('color_code', models.CharField(default='slate', help_text='Tailwind color name', max_length=20)),
                ('career', models.ForeignKey(help_text="The career this rank set belongs to. Leave null for a 'Default' set.", on_delete=django.db.models.deletion.CASCADE, related_name='ranks', to='teachers.career')),
            ],
            options={
                'ordering': ['min_rate'],
                'unique_together': {('career', 'min_rate')},
            },
        ),
    ]
